TERMUX_PKG_HOMEPAGE=https://github.com/libsdl-org/SDL_ttf
TERMUX_PKG_DESCRIPTION="A library that allows you to use TrueType fonts in your SDL applications (version 3)"
TERMUX_PKG_LICENSE="ZLIB"
TERMUX_PKG_LICENSE_FILE="LICENSE.txt"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="3.2.0"
TERMUX_PKG_SRCURL=https://github.com/libsdl-org/SDL_ttf/releases/download/release-${TERMUX_PKG_VERSION}/SDL3_ttf-${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=9a741defb7c7d6dff658d402cb1cc46c1409a20df00949e1572eb9043102eb62
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_UPDATE_VERSION_SED_REGEXP='s/.*-//'
TERMUX_PKG_DEPENDS="freetype, opengl, sdl3"
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-DSDLTTF_VENDORED=OFF
-DSDLTTF_HARFBUZZ=OFF
"
